const TYPES = {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_ERROR: 'SIGN_ERROR',
  SIGN_LOADING: 'SIGN_LOADING',

  PRODUCT_ALL: 'PRODUCT_ALL',
  PRODUCT_LOADING: 'PRODUCT_LOADING',
  PRODUCT_BY_ID: 'PRODUCT_BY_ID',

  CATEGORY_ALL: 'CATEGORY_ALL',
  CATEGORY_PRODUCTS: 'CATEGORY_PRODUCTS',
  CATEGORY_LOADING: 'CATEGORY_LOADING',

  RATING_LOADING: 'RATING_LOADING',
  RATING_CREATE: 'RATING_CREATE',

  FETCH_LOADING: 'FETCH_LOADING',
  GET_CART: 'GET_CART',
  FETCH_PRICE_DELIVERY: 'FETCH_PRICE_DELIVERY',
  REMOVE_PROD_CART: 'REMOVE_PROD_CART',
}

export default TYPES
