const TYPES = {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_ERROR: 'SIGN_ERROR',
  SIGN_LOADING: 'SIGN_LOADING',

  PRODUCT_ALL: 'PRODUCT_ALL',
  PRODUCT_LOADING: 'PRODUCT_LOADING',

  CATEGORY_ALL: 'CATEGORY_ALL',
  CATEGORY_ID: 'CATEGORY_ID',
  CATEGORY_LOADING: 'CATEGORY_LOADING'
}

export default TYPES
