const TYPES = {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_ERROR: 'SIGN_ERROR',
  SIGN_LOADING: 'SIGN_LOADING',

  PRODUCT_ALL: 'PRODUCT_ALL',
  PRODUCT_WITH_FILTER: 'PRODUCT_WITH_FILTER',
  PRODUCT_LOADING: 'PRODUCT_LOADING',
  PRODUCT_BY_ID: 'PRODUCT_BY_ID',
  PRODUCT_EDIT: 'PRODUCT_EDIT',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_REMOVE: 'PRODUCT_REMOVE',

  CATEGORY_ALL: 'CATEGORY_ALL',
  CATEGORY_PRODUCTS: 'CATEGORY_PRODUCTS',
  CATEGORY_LOADING: 'CATEGORY_LOADING',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_EDIT: 'CATEGORY_EDIT',
  CATEGORY_UPDATE: 'CATEGORY_UPDATE',
  CATEGORY_REMOVE: 'CATEGORY_REMOVE',

  RATING_LOADING: 'RATING_LOADING',
  RATING_CREATE: 'RATING_CREATE',
  RATING_LIST_ALL: 'RATING_LIST_ALL',
  RATING_REMOVE: 'RATING_REMOVE',

  CART_LOADING: 'CART_LOADING',
  ADD_CART: 'ADD_CART',
  GET_CART: 'GET_CART',
  UPDATE_CART: 'UPDATE_CART',
  CLEAN_CART: 'CLEAN_CART',
  FETCH_PRICE_DELIVERY: 'FETCH_PRICE_DELIVERY',
  REMOVE_PROD_CART: 'REMOVE_PROD_CART',

  SOLICITATION_LOADING: 'SOLICITATION_LOADING',
  SOLICITATION_CREATE: 'SOLICITATION_CREATE',
  SOLICITATION_CLIENT_LIST: 'SOLICITATION_CLIENT_LIST',
  SOLICITATION_ADMIN_LIST: 'SOLICITATION_ADMIN_LIST',

  PAYMENT_LOADING: 'PAYMENT_LOADING',
  FETCH_SESSION_ID: 'FETCH_SESSION_ID',
  FETCH_SENDER_HASH: 'FETCH_SENDER_HASH',
  PAYMENT_CREATE: 'PAYMENT_CREATE',

  CLIENT_LOADING: 'CLIENT_LOADING',
  CLIENT_ID: 'CLIENT_ID',
  CLIENT_ALL: 'CLIENT_ALL'
}

export default TYPES
